### ISSUE TITLE
关于鸟瞰图拼接

### ISSUE THREAD

**Issue by wanchenglin** [dyfcalid/CameraCalibration#2]
我使用示例的图片进行拼接，调整了输出图片的尺寸希望获得更大范围的鸟瞰图，但获得的图片却很怪，这是什么原因？
![surround](https://user-images.githubusercontent.com/90398679/163806002-355a6ae9-7700-426b-b60f-2c77a29d9b1c.jpg)

**Comment by wanchenglin** [comment]
> 我使用示例的图片进行拼接，调整了输出图片的尺寸希望获得更大范围的鸟瞰图，但获得的图片却很怪，这是什么原因？ ![surround](https://user-images.githubusercontent.com/90398679/163806002-355a6ae9-7700-426b-b60f-2c77a29d9b1c.jpg)
这个参数必须与外参标定时使用的无人机视角图片的分辨率保持一致吗？

**Comment by dyfcalid** [comment]
> 
是一致的 可以根据实际需求 在外参标定计算单应性矩阵H时手动处理成所需分辨率大小的无人机图片 并修改相应的参数

**Comment by wanchenglin** [comment]
> > 
> 
> 是一致的 可以根据实际需求 在外参标定计算单应性矩阵H时手动处理成所需分辨率大小的无人机图片 并修改相应的参数

你好，我还有一个问题，我想要做实时的鸟瞰图拼接，就像您的demo一样，这个该怎么做呢？readme里好像没有这方面的说明。
