### ISSUE TITLE
外参标定显示的转换图异常

### ISSUE THREAD

**Issue by wanchenglin** [dyfcalid/CameraCalibration#6]
您好，请问四个方位的图像有两个都显示异常，这是什么原因呢
![Screenshot from 2022-04-26 21-06-22](https://user-images.githubusercontent.com/90398679/165307597-fdbc37fc-3b1f-4916-bc8c-7280d2d28e55.png)
？

**Comment by dyfcalid** [comment]
尽量不要使用长宽角点数一样的标定板，这样算法并不能确定标定板的方向。所以上图中是因为角点的顺序不对应导致的，你可以从颜色看出来。你可以手动处理一下两张图检测出的角点坐标，让他们的顺序一一对应。

**Comment by wanchenglin** [comment]
> 尽量不要使用长宽角点数一样的标定板，这样算法并不能确定标定板的方向。所以上图中是因为角点的顺序不对应导致的，你可以从颜色看出来。你可以手动处理一下两张图检测出的角点坐标，让他们的顺序一一对应。

好的谢谢，我试试
